Daily_News/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.first_page,name=''),
    path('home', views.home_page,name=''),
    path('subscribe', include('subscribe.urls')),
    path('todays_headlines',views.today_headlines,name=''),
    path('bussiness',views.bussiness,name=''),
    path('entertainment',views.entertainment,name=''),
    path('science',views.science,name=''),
    path('health',views.health,name=''),
    path('technology',views.technology,name=''),
    path('sport',views.sport,name=''),
    path('About_us',views.About_us,name=''),

]

subscribe/urls.py
from django.urls import path
from . import views
from . import admin





urlpatterns = [
    path('',views.subscribe,name=''),
    path('/abs',views.Construct_SMS,name=''),
    path('/Contact_us', views.Contact_us, name=''),

]

subscribe/models.py
from django.db import models


class Subscribe(models.Model):
    subs_id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=50)
    phone = models.IntegerField()
    email = models.EmailField(max_length=50)
    headlines = models.BooleanField(default=True)
    bussiness = models.BooleanField(default=False)
    entertainment = models.BooleanField(default=False)
    health = models.BooleanField(default=False)
    science = models.BooleanField(default=False)
    technology = models.BooleanField(default=False)
    sports = models.BooleanField(default=False)

    def __str__(self):
        return self.name


class Contact_Us(models.Model):
    msg_id=models.AutoField(primary_key=True)
    name=models.CharField(max_length=50)
    email=models.CharField(max_length=50)
    phone=models.IntegerField()
    desc=models.CharField(max_length=500)
    def __str__(self):
        return self.name

subscribe/forms.py
from  django import forms
from .models import Subscribe


class subs_page(forms.ModelForm):
    name= forms.CharField(label='Name',
                          widget=forms.TextInput(attrs={"placeholder": "Name",
                                                        "class": "form-control",
                                                        "type": "text"
                                                        }
                                                 )
                          )
    phone=forms.IntegerField(label='Phone Number',
                             widget=forms.NumberInput(attrs={"placeholder":"Phone Number",
                                                              "class": "form-control",
                                                              "type":"tel"
                                                              }
                                                      )
                             )
    email=forms.EmailField(label='Email Address',
                           widget=forms.EmailInput(attrs={"placeholder":"Email",
                                                          "class":"form-control",
                                                         }
                                                   )
                           )
    headlines=forms.BooleanField(required=True)
    bussiness=forms.BooleanField(required=False)
    entertainment=forms.BooleanField(required=False)
    health=forms.BooleanField(required=False)
    science=forms.BooleanField(required= False)
    technology=forms.BooleanField(required=False)
    sports=forms.BooleanField(required=False)
    class Meta:
        model=Subscribe
        fields=["name",
                "phone",
                "email",
                "headlines",
                "bussiness",
                "entertainment",
                "health",
                "science",
                "technology",
                "sports"
                ]

subscribe/views.py
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
from .forms import subs_page
from .models import Subscribe, Contact_Us
import requests


def subscribe(request):
    sub = subs_page(request.POST or None)
    if sub.is_valid():
        check_num = list(Subscribe.objects.values('phone'))
        form_num = int(request.POST.get("phone", ""))
        for i in check_num:
            c = i
            for key, values in c.items():
                if form_num == values:
                    return HttpResponse("A account is already registered by this number ")
        sub.save()
        return render(request, 'Subscribe/Thanks.html')

    context = {
        "form": sub
    }
    return render(request, 'Subscribe/Subs_Form.html', context)

def  Construct_SMS(request):
    sent_to = list(Subscribe.objects.values('name', 'phone', 'email', 'headlines', 'bussiness', 'entertainment', 'health', 'science', 'technology', 'sports'))
    for i in sent_to:
        News_Matter = {}
        coustomer = i
        print(coustomer['name'])
        if coustomer['headlines'] == True:
            name = coustomer['name']
            starting_message = "Good Morning {} Here Are Some Today's Updates".format(name)
            phone = coustomer['phone']
            r = requests.get('https://newsapi.org/v2/top-headlines?country=in&apiKey=43a3a6d4d9204f8886265212e5cc2f97')
            a = 0
            news_content = {}
            news = r.json()
            o = (news["articles"])
            for i in o:
                news_title = (i["title"])
                news_desc = (i["description"])
                news_url = (i["url"])
                a += 1
                news_content[a] = {}
                news_content[a]['title'] = news_title
                news_content[a]['desc'] = news_desc
                news_content[a]['url'] = news_url
            News_Matter["Headlines"] = news_content
        if coustomer['bussiness']==True:
            r = requests.get("https://newsapi.org/v2/top-headlines?country=in&category=business&apiKey=43a3a6d4d9204f8886265212e5cc2f97")
            a = 0
            news_content = {}
            news = r.json()
            o = (news["articles"])
            for i in o:
                news_title = (i["title"])
                news_desc = (i["description"])
                news_url = (i["url"])
                a += 1
                news_content[a] = {}
                news_content[a]['title'] = news_title
                news_content[a]['desc'] = news_desc
                news_content[a]['url'] = news_url
            News_Matter["Bussiness"] = news_content
        if coustomer['entertainment']==True:
            r = requests.get("https://newsapi.org/v2/top-headlines?country=in&category=entertainment&apiKey=43a3a6d4d9204f8886265212e5cc2f97")
            a = 0
            news_content = {}
            news = r.json()
            o = (news["articles"])
            for i in o:
                news_title = (i["title"])
                news_desc = (i["description"])
                news_url = (i["url"])
                a += 1
                news_content[a] = {}
                news_content[a]['title'] = news_title
                news_content[a]['desc'] = news_desc
                news_content[a]['url'] = news_url
            News_Matter["Technology"] = news_content
        if coustomer['health']==True:
            r = requests.get
            a = 0
            news_content = {}
            news = r.json()
            o = (news["articles"])
            for i in o:
                news_title = (i["title"])
                news_desc = (i["description"])
                news_url = (i["url"])
                a += 1
                news_content[a] = {}
                news_content[a]['title'] = news_title
                news_content[a]['desc'] = news_desc
                news_content[a]['url'] = news_url
            News_Matter["Health"] = news_content
        if coustomer['science']==True:
            r = requests.get("https://newsapi.org/v2/top-headlines?country=in&category=science&apiKey=43a3a6d4d9204f8886265212e5cc2f97")
            a = 0
            news_content = {}
            news = r.json()
            o = (news["articles"])
            for i in o:
                news_title = (i["title"])
                news_desc = (i["description"])
                news_url = (i["url"])
                a += 1
                news_content[a] = {}
                news_content[a]['title'] = news_title
                news_content[a]['desc'] = news_desc
                news_content[a]['url'] = news_url
            News_Matter["Science"] = news_content
        if coustomer['technology']==True:
            r = requests.get("https://newsapi.org/v2/top-headlines?country=in&category=technology&apiKey=43a3a6d4d9204f8886265212e5cc2f97")
            a = 0
            news_content = {}
            news = r.json()
            o = (news["articles"])
            for i in o:
                news_title = (i["title"])
                news_desc = (i["description"])
                news_url = (i["url"])
                a += 1
                news_content[a] = {}
                news_content[a]['title'] = news_title
                news_content[a]['desc'] = news_desc
                news_content[a]['url'] = news_url
            News_Matter["Technology"] = news_content
        if coustomer['sports']==True:
            r = requests.get("https://newsapi.org/v2/top-headlines?country=in&category=sports&apiKey=43a3a6d4d9204f8886265212e5cc2f97")
            a = 0
            news_content = {}
            news = r.json()
            o = (news["articles"])
            for i in o:
                news_title = (i["title"])
                news_desc = (i["description"])
                news_url = (i["url"])
                a += 1
                news_content[a] = {}
                news_content[a]['title'] = news_title
                news_content[a]['desc'] = news_desc
                news_content[a]['url'] = news_url
            News_Matter["Spots"] = news_content
        return JsonResponse(News_Matter,safe=False)

def Contact_us(request):
    if request.method == "POST":
        name = request.POST.get("name", "")
        email = request.POST.get("email", "")
        phone = request.POST.get("phone", "")
        desc = request.POST.get("desc", "")
        contact = Contact_Us(name=name, email=email, phone=phone, desc=desc)
        contact.save()
        return HttpResponse("Your query has been submitted...we will answer as soon as possible...""<a href='/home'><button type='button' class='btn btn-primary'>Back To Home</button></a>")
    return render(request, 'News/Contact_us.html')

templates/Subscribe/Basics.html
<!DOCTYPE html>
<html lang="en">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <title> {% block title %} {% endblock %} </title>
    <style>{% block style %} {% endblock %}</style>
    <style>
  body{
      min-height:654px;
      max-height:100000px;
  background-image: linear-gradient(#00ace6,  #e6f9ff);
   background-repeat: no-repeat;

}
nav{
box-shadow: 0 4px 8px 0 rgba(0, 0,
0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
}
  </style>
  <body>
  <header>
<nav class="navbar navbar-expand-lg navbar-light bg-transparent">
  <a class="navbar-brand" href="">
    <img src="" width="30" height="30" class="d-inline-block align-top" alt="...">
    Express News
  </a>
<div class="collapse navbar-collapse flex-grow-1 text-right" id="myNavbar7">
        <ul class="navbar-nav ml-auto flex-nowrap">
  <li class="nav-item active">
        <a class="nav-link" href="/home">Home <span class="sr-only">(current)</span></a>
      </li>
    <li class="nav-item active">
        <a class="nav-link" href="#">About Us <span class="sr-only">(current)</span></a>
      </li>
    <li class="nav-item active">
        <a class="nav-link" href="#">Contact Us<span class="sr-only">(current)</span></a>
      </li>
  </ul>
</div>


</nav>

  </header>


<body>{% block body %}{% endblock %}</body>
    </body>

</html>

templates/Subscribe/Subs_Form.html
{% extends "News/Basics.html"%}
{% block title %} Subscribe Now..! {% endblock%}
{% block style %}

input[type="checkbox"]:checked{
box-shadow:0 0 0 3px green;
}
body{
height:654px;
}

{% endblock %}
{% block body %}
<form class="mx-3 my-3 col-6" action="/subscribe" method="post">
    {% csrf_token %}
    <div class="form-group">
        <div class="col-md-6">
        <label>Name</label>
        {{ form.name}}
            </div>
        <div class="form-group">
            <div class="col-md-6">
        <label>Phone Number</label>
        {{ form.phone}}
                </div>
            </div>
        <div class="form-group">
                        <div class="col-md-6">

        <label>Email Address</label>
            {{ form.email}}
            </div>
                        </div>


    </div>
    <div class="my-2">
    	<h6> Choose Topics As Per Your Intrests</h6>
        <div class="form-check ">
            <div class="head">
                {{ form.headlines}}
                <label for="id_headlines" >
                    Headlines
                </label>
            </div>
            <div>
                {{ form.bussiness}}
                <label for="id_bussiness" >
                    Bussiness
                </label>
            </div>
            <div>
                {{ form.entertainment}}
                <label for="id_entertainment" >
                    Entertainment
                </label>
            </div>
            <div>
                {{ form.health}}
                <label for="id_health" >
                    Health
                </label>
            </div>
            <div>
                {{ form.science}}
                <label for="id_science" >
                    Science
                </label>
            </div>
            <div>
                {{ form.technology}}
                <label for="id_technology" >
                    Technology
                </label>
            </div>
            <div>
                {{ form.sports}}
                <label for="id_sports" >
                    Sports
                </label>
            </div>
        </div>
    </div>
    <button type="submit" class="btn btn-primary">Subscribe</button>
</form>
{% endblock %}

templates/Subscribe/Thanks.html
{% extends "News/Basics.html"%}
{% block title %} Subscribe Now..! {% endblock%}
{% block style %}
body{
height:654px;
}
{% endblock %}
{% block body %}
<div class="mx-5 mt-5">
  <h1 class="display-4">Thanks....!</h1>
  <p class="lead"> You Have Successfully Subscribed To Our News Services.
      Now You Will Get Daily Top Headlines From Your Choosen Fields.   </p>
  <a class="btn btn-primary btn-lg" href="/home" role="button">Back To Home</a>
</div>

{% endblock %}